name: Tag

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Create semantic version tag
        run: node scripts/semantic-version.mjs

      - name: Push tags
        run: git push origin --tags